#!/bin/zsh

# Script d'exemples d'utilisation des modes TEST/PRODUCTION
# Usage: ./examples.sh

echo "🚀 EXEMPLES D'UTILISATION DES MODES RAG"
echo "======================================"

echo ""
echo "📋 1. PIPELINE DE VECTORISATION"
echo "-------------------------------"
echo "# Mode TEST (données réduites):"
echo "python3 pipeline.py --test"
echo ""
echo "# Mode PRODUCTION (toutes les données):"
echo "python3 pipeline.py"
echo "python3 pipeline.py --prod"
echo ""
echo "# Avec options supplémentaires:"
echo "python3 pipeline.py --test --clear-db --chunk-size 500"
echo "python3 pipeline.py --stats-only"

echo ""
echo "🧪 2. TESTS DE PERFORMANCE"
echo "-------------------------"
echo "# Mode TEST:"
echo "python3 rag_performance_test.py --test"
echo ""
echo "# Mode PRODUCTION:"
echo "python3 rag_performance_test.py"
echo "python3 rag_performance_test.py --prod"

echo ""
echo "🔄 3. GESTION DES MODES"
echo "----------------------"
echo "# Basculer via script dédié:"
echo "python3 switch_mode.py toggle"
echo "python3 switch_mode.py show"
echo ""
echo "# Voir le guide d'utilisation:"
echo "python3 usage_guide.py"

echo ""
echo "💡 4. WORKFLOWS RECOMMANDÉS"
echo "---------------------------"
echo "# Développement/Test:"
echo "python3 pipeline.py --test --clear-db"
echo "python3 rag_performance_test.py --test"
echo ""
echo "# Production:"
echo "python3 pipeline.py --prod --clear-db"
echo "python3 rag_performance_test.py --prod"

echo ""
echo "📊 5. VÉRIFICATIONS"
echo "------------------"
echo "# Statistiques de la base:"
echo "python3 pipeline.py --stats-only"
echo ""
echo "# Mode actuel:"
echo "python3 switch_mode.py show"

echo ""
echo "🗄️  BASES DE DONNÉES UTILISÉES:"
echo "-------------------------------"
echo "MODE TEST:       chatbot_test_db.data"
echo "MODE PRODUCTION: chatbot_db.data"
echo ""
echo "Note: Les arguments --test/--prod ont la priorité sur le fichier .env"
